### PR TITLE
Local test packages

### PR DESCRIPTION
**Pull request by tschorr**
Add setUp/tearDown to add test packages to pkg_resources.working_set.

### CODE REVIEW

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
The tests pass.
But I see that the setUp of test_loader now bleeds into the other tests.
I tried with these changes in buildout and tox, so the test packages are not loaded by them but only by your setUp code:

```
$ git diff
diff --git a/buildout.cfg b/buildout.cfg
index 0b4b560..c8640ac 100644
--- a/buildout.cfg
+++ b/buildout.cfg
@@ -2,13 +2,9 @@
 develop =
 # This only works when called from a tox environment.
     ../..
-    ../../test-packages/example.ploneaddon
-    ../../test-packages/example.metaoverrides
 parts = test
 
 [test]
 recipe = zc.recipe.testrunner
 eggs =
     plone.autoinclude
-    example.ploneaddon
-    example.metaoverrides
diff --git a/tox.ini b/tox.ini
index 61b1d52..a6b8822 100644
--- a/tox.ini
+++ b/tox.ini
@@ -17,8 +17,6 @@ envlist =
 usedevelop = true
 deps =
     zope.testrunner
-    test-packages/example.ploneaddon
-    test-packages/example.metaoverrides
 commands =
     zope-testrunner --test-path=src []
 extras =
```

All tox tests then pass.

But when I remove `test_loader.py`, the other tests fail because all the example packages are not found.

Since the tests still pass, it may be okay.  But can you check if you can revert the working_set change in tearDown?

**Comment by tschorr** [comment]
The last commit should clean up the working set. There's duplicate setUp/tearDown code now in the different TestPackage classes, but we could clean that up later.

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
The changes work.
When I move `setUp` and `tearDown` to base.py, and change both `TestPackage` classes to inherit from `(PackageTestCase, unittest.TestCase)` instead of the other way around, then it works.

But the problem I have with this approach, is that I think we are no longer testing the real thing. I want to test that we can find an entry point and zcml from a package that is installed with `pip install` or with buildout. Instead the code now programmatically adds a package to the working set. I don't know if this comes close to how pip and buildout do it.

So I do not think this is the right approach for all tests.
It could still be used for some unit tests, as it can be very useful to have different working sets and test a function call with those. But the tests for the packages should not use it.

Maybe you can put this in a `pytest.fixture` in `conftest.py` in a way that it is picked up automatically when you run `pytest`? So tox with zope-testrunner ignores it, but you can use pytest.
I briefly tried this, but it failed. I am no pytest expert though.

**Comment by tschorr** [comment]
> But the problem I have with this approach, is that I think we are no longer testing the real thing. I want to test that we can find an entry point and zcml from a package that is installed with `pip install` or with buildout. Instead the code now programmatically adds a package to the working set. I don't know if this comes close to how pip and buildout do it.
> 
> So I do not think this is the right approach for all tests.
> It could still be used for some unit tests, as it can be very useful to have different working sets and test a function call with those. But the tests for the packages should not use it.

To be clear, I'm only trying to provide a fixture for unit testing. It's not intended as a replacement for the tox tests you added that I think are integration tests.
But I would expect the test packages for integration tests to behave more like real world packages. E.g. tests for integration testing should be added to the test packages and not to the tests folder. Tox would then run the tests for the test package and automatically bypass the test fixtures I provide. This would open the way to more complex integration testing with actual Plone packages that currently use z3c.autoinclude but should work with plone.autoinclude.

**Comment by mauritsvanrees** [comment]
I think I see your point finally. :-) Sounds like a plan. Let me move my test code around on the main branch.

**Comment by mauritsvanrees** [comment]
Pfff, after moving the test files, I had problems letting either zope-testrunner or pytest discover them. ``--test-path=test-packages` did not work, it had to be `--test-path=test-packages/example.addon/src` and this for each test package.

Maybe I should have moved all test files directly in the `test-packages` directory instead of sprinkling them over all the packages. Not sure if that would have worked.

Anyway, the tests in the main branch are split up now, so should be closer to how you want it. Can you check? And then probably either rebase your branch or create a new PR.

I am away from keyboard for the next hour.

**Comment by tschorr** [comment]
That looks good to me now.

**Review by mauritsvanrees — APPROVED** [review]

**Review by mauritsvanrees — APPROVED** [review]
I see some stuff is wrong with how tox is setup on this branch. Only the integration tests are run, not the unit tests. And when I fix it and run the unittests, the fail because the `test-packages` directory is not found.

But let's move on. I will merge this, and will fix tox on the main branch or make a PR.

Your way of using `working_set` and `get_entry_map` is certainly better, and gives us more flexibility when needed.

**Pull request merged**
